model_dir: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/run/

data:
  train_features_file: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/train_words_bitext.txt
  train_labels_file: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/train_tags_bitext.txt
  eval_features_file: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/valid_words_bitext.txt
  eval_labels_file: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/valid_tags_bitext.txt
  source_1_vocabulary: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/src-train-vocab.txt
  source_2_vocabulary: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/src-train-tkt-vocab.txt
  target_vocabulary: C:/Users/Hanane/Documents/Python_Scripts/TelecomParis/Qwant/TP/transformation_files/tgt-train-vocab.txt